project_name: gocden
before:
  hooks:
    - go mod tidy
    - bun --cwd pkg/assets run build
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/gocden

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      deployer_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - --yes
snapshot:
  name_template: "{{ incpatch .Version }}-next"
brews:
  - repository:
      owner: lukeshay
      name: homebrew-tap
    homepage: "https://github.com/lukeshay/gocden"
    description: the gocden cli
    license: Apache-2.0
#fpms:
# - maintainer: lukeshay
#   description: the gocden cli
#   formats:
#     - deb
#     - rpm
#   file_name_template: >-
#     {{ .ProjectName }}-
#     {{- if eq .Os "darwin" }}mac
#     {{- else }}{{ .Os }}{{ end }}-{{ .Arch }}
#scoop:
#  bucket:
#    owner: lukeshay
#   name: scoop-bucket
# homepage: "https://github.com/lukeshay/gocden"
# description: "gocden cli"
# license: Apache 2.0

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
