name = 'gocden'
description = 'Documentation for gocden'
url = 'https://lukeshay.github.io/gocden'

[social]
twitter = ''
facebook = ''
instagram = ''
linkedin = ''
github = ''
gitlab = ''
bitbucket = ''

[build]
src = 'docs'
out = '_site'
assets = ''

[options]
ordering = true

[serve]
port = 7153
