name: ci

on:
  pull_request:
  push:
    branches:
      - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.22.0"
      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      - name: Go Mod
        run: go mod download
      - name: Install node_modules
        run: cd pkg/assets && bun install && bun run build
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot
      - name: Build docs
        run: ./dist/gocden_linux_amd64_v1/gocden --verbose build
