name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  goreleaser:
    runs-on: ubuntu-22.04
    environment:
      name: Release
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      packages: write
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.22.0"
      - uses: sigstore/cosign-installer@v3.3.0
      - run: go mod download
      - run: cd pkg/assets && bun install && bun run build
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.DOCGEN_GITHUB_TOKEN }}
      - run: ./dist/gocden_linux_amd64_v1/gocden --verbose build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site
          name: github-pages
      - id: deployment
        uses: actions/deploy-pages@v4
