name: release

on:
  push:
    workflow_dispatch:
    tags:
      - "v*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.22.0"
      - name: Go Mod
        run: go mod download
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.DOCGEN_GITHUB_TOKEN }}
      - name: Build docs
        run: ./dist/docgen_linux_amd64_v1 --verbose build
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./docs-gen"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
